name: Hello World and Flutter Web Build

on:
  repository_dispatch:
    types:
      - hello-world

jobs:
  build-flutter-web:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout Code from Another Repository
        uses: actions/checkout@v2
        with:
          repository: Current-Namaz/mnm-user
          ref: master  
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - name: Build Flutter Web
        uses: bluefireteam/flutter-gh-pages@v7
