name: Hello World and Flutter Web Build

on:
  repository_dispatch:
    types:
      - hello-world

jobs:
  build-flutter-web:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout Code from Another Repository
        uses: actions/checkout@v2
        with:
          repository: Current-Namaz/mnm-user
          ref: master  
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1

      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release --web-renderer=auto --base-href / 
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin gh-pages --force
      - name: Trigger Hello World Workflow
        env:
          TARGET_REPO_OWNER: Current-Namaz  # Replace with the owner of the target repository
          TARGET_REPO_NAME: mnm-user-beta-web   # Replace with the name of the target repository
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/dispatches" \
            -d '{"event_type": "sync-code"}'
