name: Build Flutter Web and Windows


on:
  repository_dispatch:
    types:
      - hello-world
  workflow_dispatch:

jobs:
  build-flutter:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"

      - name: Checkout Code from Another Repository
        uses: actions/checkout@v2
        with:
          repository: Current-Namaz/mnm-user
          ref: master
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}

      - name: Setup Flutter for Web
        uses: subosito/flutter-action@v1

      - name: Build Flutter Web
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /mnm-user-beta-web/

      - name: Setup Flutter for Windows
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter Windows
        run: |
          flutter pub get
          flutter test
          flutter build windows

      - name: Archive Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifact
          path: build/windows/

      - name: Trigger Hello World Workflow
        env:
          TARGET_REPO_OWNER: Current-Namaz
          TARGET_REPO_NAME: mnm-user-beta-web
          GITHUB_TOKEN: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$TARGET_REPO_OWNER/$TARGET_REPO_NAME/dispatches" \
            -d '{"event_type": "sync-code"}'
