name: Sync Code between Repositories

on:
  push:
    branches:
      - gh-pages
  workflow_dispatch:  # Add manual trigger
    inputs:
      destination-repo:
        description: 'Destination repository URL'
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2

      - name: Push Code to Destination Repository
        env:
          PAT_TOKEN: ${{ secrets.PAT }}
        run: |
          git remote add destination https://github.com/Current-Namaz/mnm-user-beta-web.git
          git push destination main
